# Site settings
name: Less Or More
email: holyplace@163.com
author: Holy place
url: http://www.bolocloud.com
resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/TorGor/
#baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: holy:技术大道上开拓前进！
motto: It's our wits that make us men.
banner: 技术控

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: TorGor

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

