# Site settings
name: Blog
email: holyplace@163.com
author: Zhiyuan.Gao
url: http://www.hifreud.com
resume_site: http://TorGor.github.io
github: https://github.com/TorGor/
baseurl: "/LessOrMore"
description: Actually, less is more!
meta_description: holy place：在技术的大道中开拓前行
motto: Cool.
banner: 开拓前行

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 8

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: TorGor

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

